server:
  port: 0

spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 30000
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10