CREATE TABLE IF NOT EXISTS statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar NOT NULL,
    uri varchar NOT NULL,
    ip varchar NOT NULL,
    call_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);