DROP TABLE IF EXISTS event_compilation;
DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;

CREATE TABLE IF NOT EXISTS events (
 id                 BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
 annotation         TEXT NOT NULL,
 category           BIGINT NOT NULL,
 created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
 description        TEXT     NOT NULL,
 event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
 initiator          BIGINT NOT NULL,
 location_lat       FLOAT NOT NULL,
 location_lon       FLOAT NOT NULL,
 paid               BOOLEAN NOT NULL,
 participant_limit  INTEGER NOT NULL DEFAULT 0,
 published_on       TIMESTAMP WITHOUT TIME ZONE,
 request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
 state              VARCHAR(20) NOT NULL,
 title              VARCHAR (120) NOT NULL
);


CREATE TABLE IF NOT EXISTS compilations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
pinned BOOLEAN NOT NULL,
title VARCHAR (255) NOT NULL,
CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilation (
event_id BIGINT REFERENCES events (id) ON DELETE CASCADE,
compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    author BIGINT,
    event BIGINT REFERENCES events (id) ON DELETE CASCADE
);