server:
  port: 0

grpc:
  server:
    port: 59091
    reflection-service-enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: "stats.collector"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.stats.kafka.serializer.GeneralAvroSerializer

collector:
  kafka:
    producer:
      topics:
        userAction: "stats.user-actions.v1"

logging:
  level:
    org.springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: INFO
        transaction:
          TransactionInterceptor: INFO
