syntax = "proto3";

package stats.message;

import "google/protobuf/timestamp.proto";
import "stats/messages/action_type.proto";

option java_package = "ru.practicum.client.proto";
option java_multiple_files = true;

message UserActionProto {
  int64 user_id = 1;                       //Идентификатор пользователя, совершившего действия
  int64 event_id = 2;                      //Идентификатор мероприятия
  ActionTypeProto action_type = 3;         //Тип действия
  google.protobuf.Timestamp timestamp = 4; //Временная метка действия
}